#[doc(hidden)]
use core::fmt;
#[doc(hidden)]
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Debug)]
pub enum Currency {
    /// The following is a list of active codes of official ISO 4217 currency names as of 1 April 2022.
    /// In the standard the values are called "alphabetic code", "numeric code", "minor unit", and "entity".
    USD,
    EUR,
    GBP,
    JPY,
    AUD,
    CAD,
    CHF,
    CNY,
    SEK,
    NZD,
    MXN,
    SGD,
    HKD,
    NOK,
    KRW,
    TRY,
    RUB,
    INR,
    BRL,
    ZAR,
    DKK,
    PLN,
    TWD,
    THB,
    IDR,
    HUF,
    CZK,
    ILS,
    CLP,
    PHP,
    AED,
    COP,
    SAR,
    MYR,
    RON,
    PEN,
    VND,
    NGN,
    UAH,
    PKR,
    IQD,
    QAR,
    KZT,
    BHD,
    OMR,
    KWD,
    DZD,
    LKR,
    BGN,
    BDT,
    MAD,
    VEF,
    XOF,
    LBP,
    UZS,
    AZN,
    TND,
    GTQ,
    BOB,
    PYG,
    PAB,
    SVC,
    NIO,
    HNL,
    CRC,
    DOP,
    BWP,
    ISK,
    XAF,
    TZS,
    GHS,
    UGX,
    MZN,
    RSD,
    MMK,
    LYD,
    GEL,
    XCD,
    BSD,
    FJD,
    MUR,
    KYD,
    JMD,
    GYD,
    MOP,
    TTD,
    BND,
    XPF,
    NAD,
    PGK,
    LAK,
    BMD,
    KHR,
    MVR,
    GNF,
    ALL,
    MWK,
    ZMW,
    MGA,
    ERN,
    SCR,
    CVE,
    SRD,
    STD,
    CDF,
    RWF,
    ANG,
    SBD,
    SOS,
    HTG,
    GMD,
    KGS,
    TJS,
    KPW,
    MNT,
    CUP,
    SLL,
    TOP,
    MRO,
    LSL,
    SZL,
    BZD,
    GWP,
    FKP,
    SHP,
    SSP,
}

impl fmt::Display for Currency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Currency::USD => write!(f, "USD"),
            Currency::EUR => write!(f, "EUR"),
            Currency::GBP => write!(f, "GBP"),
            Currency::JPY => write!(f, "JPY"),
            Currency::AUD => write!(f, "AUD"),
            Currency::CAD => write!(f, "CAD"),
            Currency::CHF => write!(f, "CHF"),
            Currency::CNY => write!(f, "CNY"),
            Currency::SEK => write!(f, "SEK"),
            Currency::NZD => write!(f, "NZD"),
            Currency::MXN => write!(f, "MXN"),
            Currency::SGD => write!(f, "SGD"),
            Currency::HKD => write!(f, "HKD"),
            Currency::NOK => write!(f, "NOK"),
            Currency::KRW => write!(f, "KRW"),
            Currency::TRY => write!(f, "TRY"),
            Currency::RUB => write!(f, "RUB"),
            Currency::INR => write!(f, "INR"),
            Currency::BRL => write!(f, "BRL"),
            Currency::ZAR => write!(f, "ZAR"),
            Currency::DKK => write!(f, "DKK"),
            Currency::PLN => write!(f, "PLN"),
            Currency::TWD => write!(f, "TWD"),
            Currency::THB => write!(f, "THB"),
            Currency::IDR => write!(f, "IDR"),
            Currency::HUF => write!(f, "HUF"),
            Currency::CZK => write!(f, "CZK"),
            Currency::ILS => write!(f, "ILS"),
            Currency::CLP => write!(f, "CLP"),
            Currency::PHP => write!(f, "PHP"),
            Currency::AED => write!(f, "AED"),
            Currency::COP => write!(f, "COP"),
            Currency::SAR => write!(f, "SAR"),
            Currency::MYR => write!(f, "MYR"),
            Currency::RON => write!(f, "RON"),
            Currency::PEN => write!(f, "PEN"),
            Currency::VND => write!(f, "VND"),
            Currency::NGN => write!(f, "NGN"),
            Currency::UAH => write!(f, "UAH"),
            Currency::PKR => write!(f, "PKR"),
            Currency::IQD => write!(f, "IQD"),
            Currency::QAR => write!(f, "QAR"),
            Currency::KZT => write!(f, "KZT"),
            Currency::BHD => write!(f, "BHD"),
            Currency::OMR => write!(f, "OMR"),
            Currency::KWD => write!(f, "KWD"),
            Currency::DZD => write!(f, "DZD"),
            Currency::LKR => write!(f, "LKR"),
            Currency::BGN => write!(f, "BGN"),
            Currency::BDT => write!(f, "BDT"),
            Currency::MAD => write!(f, "MAD"),
            Currency::VEF => write!(f, "VEF"),
            Currency::XOF => write!(f, "XOF"),
            Currency::LBP => write!(f, "LBP"),
            Currency::UZS => write!(f, "UZS"),
            Currency::AZN => write!(f, "AZN"),
            Currency::TND => write!(f, "TND"),
            Currency::GTQ => write!(f, "GTQ"),
            Currency::BOB => write!(f, "BOB"),
            Currency::PYG => write!(f, "PYG"),
            Currency::PAB => write!(f, "PAB"),
            Currency::SVC => write!(f, "SVC"),
            Currency::NIO => write!(f, "NIO"),
            Currency::HNL => write!(f, "HNL"),
            Currency::CRC => write!(f, "CRC"),
            Currency::DOP => write!(f, "DOP"),
            Currency::BWP => write!(f, "BWP"),
            Currency::ISK => write!(f, "ISK"),
            Currency::XAF => write!(f, "XAF"),
            Currency::TZS => write!(f, "TZS"),
            Currency::GHS => write!(f, "GHS"),
            Currency::UGX => write!(f, "UGX"),
            Currency::MZN => write!(f, "MZN"),
            Currency::RSD => write!(f, "RSD"),
            Currency::MMK => write!(f, "MMK"),
            Currency::LYD => write!(f, "LYD"),
            Currency::GEL => write!(f, "GEL"),
            Currency::XCD => write!(f, "XCD"),
            Currency::BSD => write!(f, "BSD"),
            Currency::FJD => write!(f, "FJD"),
            Currency::MUR => write!(f, "MUR"),
            Currency::KYD => write!(f, "KYD"),
            Currency::JMD => write!(f, "JMD"),
            Currency::GYD => write!(f, "GYD"),
            Currency::MOP => write!(f, "MOP"),
            Currency::TTD => write!(f, "TTD"),
            Currency::BND => write!(f, "BND"),
            Currency::XPF => write!(f, "XPF"),
            Currency::NAD => write!(f, "NAD"),
            Currency::PGK => write!(f, "PGK"),
            Currency::LAK => write!(f, "LAK"),
            Currency::BMD => write!(f, "BMD"),
            Currency::KHR => write!(f, "KHR"),
            Currency::MVR => write!(f, "MVR"),
            Currency::GNF => write!(f, "GNF"),
            Currency::ALL => write!(f, "ALL"),
            Currency::MWK => write!(f, "MWK"),
            Currency::ZMW => write!(f, "ZMW"),
            Currency::MGA => write!(f, "MGA"),
            Currency::ERN => write!(f, "ERN"),
            Currency::SCR => write!(f, "SCR"),
            Currency::CVE => write!(f, "CVE"),
            Currency::SRD => write!(f, "SRD"),
            Currency::STD => write!(f, "STD"),
            Currency::CDF => write!(f, "CDF"),
            Currency::RWF => write!(f, "RWF"),
            Currency::ANG => write!(f, "ANG"),
            Currency::SBD => write!(f, "SBD"),
            Currency::SOS => write!(f, "SOS"),
            Currency::HTG => write!(f, "HTG"),
            Currency::GMD => write!(f, "GMD"),
            Currency::KGS => write!(f, "KGS"),
            Currency::TJS => write!(f, "TJS"),
            Currency::KPW => write!(f, "KPW"),
            Currency::MNT => write!(f, "MNT"),
            Currency::CUP => write!(f, "CUP"),
            Currency::SLL => write!(f, "SLL"),
            Currency::TOP => write!(f, "TOP"),
            Currency::MRO => write!(f, "MRO"),
            Currency::LSL => write!(f, "LSL"),
            Currency::SZL => write!(f, "SZL"),
            Currency::BZD => write!(f, "BZD"),
            Currency::GWP => write!(f, "GWP"),
            Currency::FKP => write!(f, "FKP"),
            Currency::SHP => write!(f, "SHP"),
            Currency::SSP => write!(f, "SSP"),
        }
    }
}
