


[env]
MTN_API_KEY = "fad2514dbf894c66a91facd483e2cfbf"
MTN_API_USER = "4fcfcdc4-1099-4a3d-9f2f-803940572dc5"
MTN_COLLECTION_PRIMARY_KEY = "c87a821c32b44eacb420b4968b2fcd2f"
MTN_COLLECTION_SECONDARY_KEY = "0b9dca174b0746b78f116b26672a8116"
MTN_DISBURSEMENT_PRIMARY_KEY = "c1861c073bf54addbb56481d6977eebf"
MTN_DISBURSEMENT_SECONDARY_KEY = "c58b67e3934b44bbabe65fb88fa33b96"
MTN_REMITTANCE_PRIMARY_KEY = "62b479e1f41441cda28eb24dff4fc067"
MTN_REMITTANCE_SECONDARY_KEY = "3766f4a178534847a2cce411041ffaac"
MTN_URL = "https://sandbox.momodeveloper.mtn.com"
MTN_CALLBACK_HOST = "momotest.boursenumeriquedafrique.com"
CALLBACK_SERVER_URL="http://momotest.boursenumeriquedafrique.com"
TLS_CERT_PATH="/home/ondonda/bna/certs/config/live/momotest.boursenumeriquedafrique.com/fullchain.pem"
TLS_KEY_PATH="/home/ondonda/bna/certs/config/live/momotest.boursenumeriquedafrique.com/privkey.pem"
