


[env]
MTN_API_KEY = "fad2514dbf894c66a91facd483e2cfbf"
MTN_API_USER = "4fcfcdc4-1099-4a3d-9f2f-803940572dc5"
MTN_COLLECTION_PRIMARY_KEY = "c19aabaac34a43a8a3786909ed0d6b31"
MTN_COLLECTION_SECONDARY_KEY = "98b4b6300b6242059a9029f00f6afe54"
MTN_DISBURSEMENT_PRIMARY_KEY = "c1861c073bf54addbb56481d6977eebf"
MTN_DISBURSEMENT_SECONDARY_KEY = "c58b67e3934b44bbabe65fb88fa33b96"
MTN_REMITTANCE_PRIMARY_KEY = "62b479e1f41441cda28eb24dff4fc067"
MTN_REMITTANCE_SECONDARY_KEY = "3766f4a178534847a2cce411041ffaac"
MTN_URL = "https://sandbox.momodeveloper.mtn.com"
MTN_CALLBACK_HOST = "ngrok.boursenumeriquedafrique.com"
CALLBACK_SERVER_URL="https://your-domain.com"
TLS_CERT_PATH="cert.pem"
TLS_KEY_PATH="key.pem"
