name: Testing the application
run-name: MTNMomo Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install nitghly
        run: |
            rustup install nightly
            rustup default nightly

      - name: test
        run: cargo test

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release create $tag ./target/release/*